# 实验 4-2：加载数据 (Load Data)

## 一维数组切片 (Slicing 1D Array)

In [3]:
nums = [0, 1, 2, 3, 4]

In [5]:
print(nums)

[0, 1, 2, 3, 4]


获取索引 2 到 4 之前的元素。（包含起始索引，不包含结束索引）

In [6]:
print(nums[2:4])

[2, 3]


获取从索引 2 开始的所有元素。

In [7]:
print(nums[2:])

[2, 3, 4]


获取索引 2 之前的元素。（同样不包含结束索引）

In [8]:
print(nums[:2])

[0, 1]


获取所有元素

In [9]:
print(nums[:])

[0, 1, 2, 3, 4]


获取最后一个索引之前的元素。（不包含最后一个！）

In [10]:
print(nums[:-1])

[0, 1, 2, 3]


也可以进行赋值！

In [11]:
nums[2:4] = [8, 9]

In [12]:
print(nums)

[0, 1, 8, 9, 4]


## 二维数组切片 (Slicing 2D Array)

In [13]:
import numpy as np

In [14]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [15]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
b[:, 1]

array([ 2,  6, 10])

In [17]:
b[-1]

array([ 9, 10, 11, 12])

In [18]:
b[-1, :]

array([ 9, 10, 11, 12])

In [19]:
b[-1, ...]

array([ 9, 10, 11, 12])

In [23]:
b[0:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## 从 .csv 文件加载数据 (Loading Data from `.csv` file)

In [24]:
import numpy as np

In [26]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)

delimiter=','说明每一列数据是用逗号分隔的，那么每一行会被拆成  个数字。

In [28]:
print(xy)

[[ 73.  80.  75. 152.]
 [ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]
 [ 69.  74.  77. 149.]
 [ 47.  56.  60. 115.]
 [ 87.  79.  90. 175.]
 [ 79.  70.  88. 164.]
 [ 69.  70.  73. 141.]
 [ 70.  65.  74. 141.]
 [ 93.  95.  91. 184.]
 [ 79.  80.  73. 152.]
 [ 70.  73.  78. 148.]
 [ 93.  89.  96. 192.]
 [ 78.  75.  68. 147.]
 [ 81.  90.  93. 183.]
 [ 88.  92.  86. 177.]
 [ 78.  83.  77. 159.]
 [ 82.  86.  90. 177.]
 [ 86.  82.  89. 175.]
 [ 78.  83.  85. 175.]
 [ 76.  83.  71. 149.]
 [ 96.  93.  95. 192.]]


In [29]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
print(x_data)
print(y_data)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [30]:
print(x_data.shape) # x_data shape
print(len(x_data))  # x_data 长度
print(x_data[:5])   # 前五个

(25, 3)
25
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]


In [31]:
print(y_data.shape) # y_data shape
print(len(y_data))  # y_data 长度
print(y_data[:5])   # 前五个

(25, 1)
25
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


## 导入库

In [32]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [33]:
# 为了可复现性
torch.manual_seed(1)

## 低级实现 (Low-level Implementation)

In [34]:
# 数据
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)
# 模型初始化
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# 优化器设置
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    
    # 计算 H(x)
    hypothesis = x_train.matmul(W) + b # or .mm or @

    # 计算 cost
    cost = torch.mean((hypothesis - y_train) ** 2)

    # 通过 cost 改善 H(x)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 每 100 次打印日志
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/20 Cost: 26811.960938
Epoch    1/20 Cost: 9920.530273
Epoch    2/20 Cost: 3675.298828
Epoch    3/20 Cost: 1366.260498
Epoch    4/20 Cost: 512.542419
Epoch    5/20 Cost: 196.896622
Epoch    6/20 Cost: 80.190987
Epoch    7/20 Cost: 37.038692
Epoch    8/20 Cost: 21.081335
Epoch    9/20 Cost: 15.178760
Epoch   10/20 Cost: 12.993677
Epoch   11/20 Cost: 12.183030
Epoch   12/20 Cost: 11.880535
Epoch   13/20 Cost: 11.765964
Epoch   14/20 Cost: 11.720856
Epoch   15/20 Cost: 11.701438
Epoch   16/20 Cost: 11.691510
Epoch   17/20 Cost: 11.685122
Epoch   18/20 Cost: 11.680007
Epoch   19/20 Cost: 11.675372
Epoch   20/20 Cost: 11.670942


## 使用 `nn.Module` 的高级实现 (High-level Implementation with `nn.Module`)

In [35]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)

In [36]:
# 数据
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)
# 模型初始化
model = MultivariateLinearRegressionModel()
# 优化器设置
optimizer = optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs+1):
    
    # 计算 H(x)
    prediction = model(x_train)
    
    # 计算 cost
    cost = F.mse_loss(prediction, y_train)
    
    # 通过 cost 改善 H(x)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 每 20 次打印日志
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/20 Cost: 28693.490234
Epoch    1/20 Cost: 10618.750977
Epoch    2/20 Cost: 3936.015381
Epoch    3/20 Cost: 1465.219727
Epoch    4/20 Cost: 551.693726
Epoch    5/20 Cost: 213.934616
Epoch    6/20 Cost: 89.052269
Epoch    7/20 Cost: 42.876007
Epoch    8/20 Cost: 25.799639
Epoch    9/20 Cost: 19.482420
Epoch   10/20 Cost: 17.143093
Epoch   11/20 Cost: 16.274508
Epoch   12/20 Cost: 15.949721
Epoch   13/20 Cost: 15.825986
Epoch   14/20 Cost: 15.776565
Epoch   15/20 Cost: 15.754660
Epoch   16/20 Cost: 15.742919
Epoch   17/20 Cost: 15.734917
Epoch   18/20 Cost: 15.728307
Epoch   19/20 Cost: 15.722219
Epoch   20/20 Cost: 15.716357


## 数据集与数据加载器 (Dataset and DataLoader)

如果数据太大，我们不能一次性加载所有的 `x_data` 和 `y_data`，只能按需加载必要的批次 (batch)。

# Dataset

**是什么：**

一个“数据访问接口”。

**作用：**

定义：
1. 数据一共有多少个样本
2. 如何获取第 i 个样本

**必须实现的两个方法：**

- `__len__()`      → 返回样本总数  
- `__getitem__(i)` → 返回第 i 个样本 (x, y)

**本质：**

一个索引到样本的映射：

    i → (x_i, y_i)


# DataLoader

**是什么：**

一个“数据批量迭代器”。

**作用：**

把 Dataset 中的样本：
- 按 batch_size 分批
- 可选打乱 (shuffle)
- 迭代输出给模型

**使用方式：**

    for x, y in dataloader:

**本质：**

把单个样本：

    (x_i, y_i)

组织成批数据：

    [(x_1,y_1), ..., (x_b,y_b)]


# 二者关系

Dataset：定义“数据长什么样”  
DataLoader：定义“数据怎么被送进模型”

[PyTorch 数据加载和处理教程](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html#iterating-through-the-dataset)