# Pytorch张量  
## 1.Pytorch张量是什么  
张量 (Tensors) 是 PyTorch 的基本数据类型，张量是类似于 NumPy 中的多维矩阵 ndarrays： 
   
1.标量可以表示为零维张量​  
2.向量可以表示为一维张量​  
3.二维矩阵可以表示为二维张量​  
4.多维矩阵可以表示为多维张量  

![张量表示](../Images/2.png)


例如，我们可以将彩色图像视为像素值的三维张量，因为彩色图像由 h x w x 3 个像素组成，其中，h 和 w 分别表示图像的高和宽，三个通道对应于 RGB 通道。类似地，灰度图像可以表示为 2 维张量，因为它由 h x w 个像素组成。  
## 2.张量初始化  
张量除了可以用作图像的基本数据结构外，另一种常见用途是利用张量来初始化连接神经网络不同层的权重。接下来，我们将学习初始化张量对象的不同方法。

1. 导入Pytorch并在列表上调用torch.tensor来初始化张量：

In [62]:
import torch
x = torch.tensor([[1,2]])
y = torch.tensor([[1],[2]])

2. 获取张量对象的形状和数据类型

In [63]:
print(x.shape)
print(y.shape)
print(x.dtype)

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


同一张量中的所有元素的数据类型相同，这意味着如果张量包含不同数据类型的数据(例如布尔、整数和浮点数)，则整个张量将被强制转换为最通用的数据类型：

In [64]:
x = torch.tensor([False, 1, 2.0])
print(x)

tensor([0., 1., 2.])


在以上输出结果中可以看到，布尔值 False 和整数 1 被转换为浮点数。  
  
类似于 NumPy，我们也可以使用内置函数初始化张量对象，以便用于神经网络的权重初始化。  
3. 生成一个3行4列用0填充的张量对象

In [65]:
a = torch.zeros((3, 4))
print(a)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


4. 生成一个3行4列用1填充的张量对象：

In [66]:
b = torch.ones((3, 4))
print(b)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


5. 生成 3 行 4 列的张量对象，其中每个元素为 0 到 10 之间的随机整数值：

In [67]:
c = torch.randint(low=0, high=10, size=(3,4))
print(c)

tensor([[0, 6, 3, 3],
        [5, 1, 3, 0],
        [5, 7, 6, 2]])


6. 生成 3 行 4 列的张量对象，其中每个元素为 0 到 1 之间的随机浮点值：

In [68]:
d = torch.rand(3, 4)
print(d)

tensor([[0.5329, 0.9715, 0.3659, 0.7690],
        [0.5348, 0.9889, 0.2566, 0.0632],
        [0.3113, 0.9164, 0.7330, 0.5665]])


7. 生成 3 行 4 列的张量对象，其中每个元素服从正态分布:

In [69]:
e = torch.randn((3,4))
print(e)

tensor([[ 0.1345,  0.9671, -0.7061, -0.2076],
        [-0.4681, -0.7989, -1.9393, -0.0356],
        [-1.2529, -0.3593, -0.9085,  0.7706]])


8. 也可以使用torch.tensor(<numpy-array>)直接将Numpy数组转换为Torch张量：

In [70]:
import numpy as np
x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>


## 3.张量运算  
与 NumPy 类似，张量对象同样可以执行各种基本运算，神经网络中的常见运算包括输入与权重的矩阵相乘、添加偏置项、以及在需要时整形 (reshape) 输入或权重值。  
1. 将x中所有元素乘10：

In [71]:
import torch
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
print(x * 10)

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])


2. 将x中所有元素加10，并将结果张量储存在y中：

In [95]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
y = x.add(10)
print(y)
print(y+10)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])
tensor([[21, 22, 23, 24],
        [25, 26, 27, 28]])


3. 使用view()方法对张量进行整形

In [73]:
y = torch.tensor([2, 3, 1, 0])
y = y.view(4, 1)
print(y)

tensor([[2],
        [3],
        [1],
        [0]])


4. 整形张量的另一种方法是使用 squeeze 方法，需要提供要删除的轴索引，需要注意的是，这仅适用于要删除的轴在该维度中只有一项时:

In [74]:
x = torch.randn(10,1,10)
z1 = torch.squeeze(x, 1)
z2 = x.squeeze(1)
assert torch.all(z1 == z2)
print('Squeeze:\n', x.shape, z1.shape)

Squeeze:
 torch.Size([10, 1, 10]) torch.Size([10, 10])


>核心思想：squeeze 就是移除大小为1的多余维度，让张量更紧凑，这在神经网络中处理批量数据时很常见。

5. unsqueeze,向矩阵添加一个维度

In [75]:
x = torch.randn(10,10)
print(x.shape)

z1 = x.unsqueeze(0)
print(z1.shape)

z2, z3, z4 = x[None], x[:,None], x[:,:,None]
print(z2.shape, z3.shape, z4.shape)

torch.Size([10, 10])
torch.Size([1, 10, 10])
torch.Size([1, 10, 10]) torch.Size([10, 1, 10]) torch.Size([10, 10, 1])


>使用 None 进行索引是一种重要的解压方式，通常用于创建新通道/维度。

6. 执行两个不同张量的矩阵乘法：

In [76]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
print(torch.matmul(x,y))
print(x@y)

tensor([[11],
        [35]])
tensor([[11],
        [35]])


7. 可以使用cat方法执行张量连接：

In [77]:
import torch
x = torch.randn(10, 10, 10)

z = torch.cat([x,x], axis=0)
print('Cat axis 0:',x.shape, z.shape)

z = torch.cat([x,x], axis=1)
print('Cat axis 1:',x.shape, z.shape)

Cat axis 0: torch.Size([10, 10, 10]) torch.Size([20, 10, 10])
Cat axis 1: torch.Size([10, 10, 10]) torch.Size([10, 20, 10])


8. 提取张量中最大值

In [78]:
x = torch.arange(25).reshape(5,5)
print('Max:',x.shape, x.max())
x.max(dim=0)
#沿着第一个维度（行方向/垂直方向）查找最大值,返回每列的最大值以及这些最大值所在行的索引。

Max: torch.Size([5, 5]) tensor(24)


torch.return_types.max(
values=tensor([20, 21, 22, 23, 24]),
indices=tensor([4, 4, 4, 4, 4]))

>max() 方法可以返回最大值和最大值的位置 (argmax)。  
>dim=0,跨行取最大值  
>dim=0,跨列取最大值

In [79]:
m, argm = x.max(dim=1)
print('Max in axis 1:\n', m, argm)

Max in axis 1:
 tensor([ 4,  9, 14, 19, 24]) tensor([4, 4, 4, 4, 4])


>min 操作与 max 完全相同，其返回最小值和最小值的位置 (argmin)

8. 重排 (permute) 张量对象的维度，当在原始张量之上执行 permute 时，张量的形状会发生变化：

In [80]:
x = torch.randn(10,20,30)
z = x.permute(2,0,1)
print('Permute dimensions:', x.shape, z.shape)

Permute dimensions: torch.Size([10, 20, 30]) torch.Size([30, 10, 20])


>避免使用 tensor.view 张量交换对象维度，即使 PyTorch 不会抛出错误，但这会在训练期间产生无法预料的结果，如果需要交换维度，推荐使用 permute。

9. 使用 dir(torch.Tensor) 查看 PyTorch 张量的所有可用方法，使用 help(torch.Tensor.<method>) 可以查看该方法的官方帮助文档。

In [81]:
dir(torch.Tensor)
help(torch.Tensor.view)

Help on method_descriptor:

view(...)
    view(*shape) -> Tensor
    
    Returns a new tensor with the same data as the :attr:`self` tensor but of a
    different :attr:`shape`.
    
    The returned tensor shares the same data and must have the same number
    of elements, but may have a different size. For a tensor to be viewed, the new
    view size must be compatible with its original size and stride, i.e., each new
    view dimension must either be a subspace of an original dimension, or only span
    across original dimensions :math:`d, d+1, \dots, d+k` that satisfy the following
    contiguity-like condition that :math:`\forall i = d, \dots, d+k-1`,
    
    .. math::
    
      \text{stride}[i] = \text{stride}[i+1] \times \text{size}[i+1]
    
    Otherwise, it will not be possible to view :attr:`self` tensor as :attr:`shape`
    without copying it (e.g., via :meth:`contiguous`). When it is unclear whether a
    :meth:`view` can be performed, it is advisable to use :meth:`resh

## 4.张量对象的自动梯度运算  
微分和计算梯度在更新神经网络的权重中起着至关重要的作用，PyTorch 的张量对象内置梯度计算函数。  

1. 定义一个张量对象，同时指定它需要的计算梯度

In [82]:
import numpy as np
import torch
x = torch.tensor([[2., -1.], [1., 1.]], requires_grad=True)
 #requires_grad 参数指定要为张量对象计算梯度。
print(x)

tensor([[ 2., -1.],
        [ 1.,  1.]], requires_grad=True)


2. 定义计算输出的方法，计算所有输入的平方和：

In [83]:
out = x.pow(2).sum()

3.  通过对该值调用 backward() 方法来计算该值的梯度

In [84]:
out.backward() #使用链式法则进行反向传播。自动计算out关于x的梯度，将梯度储存在x.grad属性之中

4. 计算得到out关于x的梯度

In [85]:
print(x.grad)

tensor([[ 4., -2.],
        [ 2.,  2.]])


到目前为止，我们已经了解了在张量对象的初始化、基本运算和梯度计算——它们共同构成了神经网络的基本组件。

## 4.Pytorch张量相对于Numpy数组的优势

在计算最佳权重值时，会对每个权重进行微量修改，并观察它对降低损失值的影响。需要注意的是，一个权重更新的损失计算不影响同一迭代中其他权重更新的损失计算。因此，每个权重更新可以由不同的核心并行进行，而非顺序更新权重，在这种情况下，GPU 与 CPU 相比更具优势，因为 GPU 通常包含数千个核心。  

与 NumPy 相比，PyTorch 张量对象经过优化以配合 GPU 使用。接下来，我们比较使用 NumPy 数组 (ndarray) 和 Tensor 张量 (tensor) 执行矩阵乘法所花费的时间。

1. 生成两个不同的torch对象：

In [86]:
import torch
import time
size = 2000
x = torch.rand(size, size, dtype=torch.float32)
y = torch.rand(size, size, dtype=torch.float32)

2. 定义用于 储存张量对象的设备

In [87]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
assert device == 'cuda', "This exercise is on a GPU machine"

3. 将步骤 1 中创建的张量对象注册到设备中，注册张量对象意味着将信息存储在指定设备中：

In [88]:
x, y = x.to(device), y.to(device)

4. 执行Torch对象的矩阵乘法，并对其计时，并比较在 NumPy 数组上执行矩阵乘法的速度：

In [89]:
import torch
import time

# 预热
for i in range(10):
    i = x @ y
torch.cuda.synchronize()

start = time.time()
for i in range(50):
    z = x @ y
torch.cuda.synchronize()
end = time.time()
print(f'GPU({size}x{size})平均: {(end-start)/50:.8f}秒')

GPU(2000x2000)平均: 0.00935949秒


5. 在 cpu 上执行相同的张量矩阵乘法：

In [90]:
# 数据移回CPU
x_cpu = x.cpu()
y_cpu = y.cpu()

# CPU测试（必须重置start！）
start = time.time()
for i in range(50):
    z = x_cpu @ y_cpu
end = time.time()
print(f'CPU(Torch)每次平均: {(end-start)/50:.8f}秒')

CPU(Torch)每次平均: 0.01099545秒


6. 在 NumPy 数组上执行相同的矩阵乘法：

In [91]:
import numpy as np

# 转为NumPy数组
x_np = x_cpu.numpy()
y_np = y_cpu.numpy()

start = time.time()
for i in range(50):
    z_np = x_np @ y_np
end = time.time()
print(f'NumPy每次平均: {(end-start)/50:.8f}秒')

NumPy每次平均: 0.01930337秒


- 最快：在GPU上Torch对象
- 第二快：在CPU上对Torch
- 最慢：在CPU上用Numpy 
   
---

## 小结  
我们学习了如何使用 PyTorch 的张量对象实现神经网络的基本组件，包括张量对象的初始化 (torch.tensor)、基本运算 (view、max、min、和 squeeze 等) 和梯度计算 (通过 requires_grad 参数指定要为张量对象计算梯度)，并且对比了 PyTorch 张量相对于 NumPy 数组的优势。